### ISSUE TITLE
Possible bug in example and missing dependancies

### ISSUE THREAD

**Issue by um-pdavila** [shahcompbio/signals#44]
Hi,

Thank you for your excellent work!!!

I found a couple issues running your example.  Posting here in case it's not just a me issue.

### Missing Dependancies in your installation documentation

I also had to install the R ggtree package before installing signals.
> devtools::install_github("YuLab-SMU/ggtree")
          
I also had to install the **VGAM** and R packages to run the example.  Possibly also the **betareg and aod*** R packages as well, though not sure.  I'll confirm later today with a new R module, and update here.
> install.packages("VGAM")
> install.packages("betareg")
> install.packages("aod")

### Error in example, screenshot below.

The second:
  hscn <- callAlleleSpecificCN(CNbins, haplotypes)

Should be:
  **a**scn <- callAlleleSpecificCN(CNbins, haplotypes)

<img width="640" alt="Screen Shot 2023-04-29 at 1 27 31 PM" src="https://user-images.githubusercontent.com/6089584/235315932-f5e69dd8-d34b-430a-8441-9a16c4b98232.png">

**Comment by marcjwilliams1** [comment]
@um-pdavila just an additional note that the vignette in the documentation is more fully featured and should be correct https://shahcompbio.github.io/signals/articles/ASCN.html

**Comment by marcjwilliams1** [comment]
I've realised that to install the suggests packages with install_github requires an additional parameter:
`install_github('shahcompbio/signals', dependencies = TRUE)`

This has been included in the docker in #48
