### ISSUE TITLE
Get the CNbins from the output of HMMcopy

### ISSUE THREAD

**Issue by xikanfeng2** [shahcompbio/signals#58]
I want to obtain the input CNbins by transforming the output files from HMMCopy. In the corrected_copy output of HMMCopy, which column should I use as the copy column for CNbins of signals?

<img width="1242" alt="截屏2024-10-21 17 50 37" src="https://github.com/user-attachments/assets/fd3c2108-a11a-4651-bd71-a911b9e5395f">

**Comment by marcjwilliams1** [comment]
you can use the copy column

**Comment by xikanfeng2** [comment]
> you can use the copy column

Thanks for your quick response. I will try.
