### ISSUE TITLE
unexpected results generated by ascn <- callAlleleSpecificCN(CNbins, haplotypes) command.

### ISSUE THREAD

**Issue by xikanfeng2** [shahcompbio/signals#59]
In our case, the input CNbins object was obtained by transforming the output files of HMMCopy. As you suggested in the last issue, we used the copy column of HMMCopy as the copy value in the CNbins object, and the state value of HMMCopy as the state value in the CNbins object. The two images below show the outputs of HMMCopy for one normal BAM file. According to the HMMCopy documentation, a state value of 3 indicates neutral (third picture). Therefore, our input for signals shoule be correct.

However, the output generated by the command ascn <- callAlleleSpecificCN(CNbins, haplotypes) is unexpected. All the state_AS_phased values for the normal BAM file are showing as 3|0 ( the forth picrture), while we expected to see 1|1 for a normal sample. I suspect that these incorrect results are due to the copy and state values in our CNbins object.

My question is: how can we correct the copy and state values in the CNbins generated by HMMCopy to ensure the output from signals is accurate?
 
<img width="1265" alt="截屏2024-10-24 21 38 13" src="https://github.com/user-attachments/assets/52d68f86-9180-419b-900c-a011ebd76622">

<img width="148" alt="截屏2024-10-24 21 40 18" src="https://github.com/user-attachments/assets/b581c444-015e-475e-a221-a97fad6710bf">

<img width="641" alt="截屏2024-10-24 21 42 13" src="https://github.com/user-attachments/assets/c1cf3bda-6f48-4c58-bce9-a1925f81ae74">

<img width="879" alt="截屏2024-10-24 21 48 30" src="https://github.com/user-attachments/assets/a03c91e8-22eb-4e41-996c-41d27b9450bd">

**Comment by marcjwilliams1** [comment]
Hello, the state column should be the total copy number so for a diploid state it should be 2. So you can subtract 1 from the states you listed above.

However, it looks like you might be using default HMMcopy parameters. We have found that single-cell data requires modifying these parameters. Some resources that will help:
- Our pipeline for running DLP data is [here](https://mondrian-scwgs.github.io/mondrian_nf/#/README)
- A lightweight script for running HMMcopy can be found [here](https://github.com/marcjwilliams1/hscn_pipeline/blob/main/scripts/run_hmmcopy.R), this is slightly outdated but will get you reasonable results if you don't want to run the whole mondrian pipeline

Another thing I would suggest is to plot the total copy number data to check it seems reasonable.
For example:
```
plotHeatmap(CNbins, plotcol = "state") #clusters and plots the total copy number state
plotHeatmap(CNbins, plotcol = "copy") #plots the raw "copy" data
```

or for plotting some individual cells:
```
plotCNprofile(CNbins, cellid = "cell_of_interest")
```

**Comment by xikanfeng2** [comment]
> Hello, the state column should be the total copy number so for a diploid state it should be 2. So you can subtract 1 from the states you listed above.
> 
> However, it looks like you might be using default HMMcopy parameters. We have found that single-cell data requires modifying these parameters. Some resources that will help:
> 
> * Our pipeline for running DLP data is [here](https://mondrian-scwgs.github.io/mondrian_nf/#/README)
> * A lightweight script for running HMMcopy can be found [here](https://github.com/marcjwilliams1/hscn_pipeline/blob/main/scripts/run_hmmcopy.R), this is slightly outdated but will get you reasonable results if you don't want to run the whole mondrian pipeline
> 
> Another thing I would suggest is to plot the total copy number data to check it seems reasonable. For example:
> 
> ```
> plotHeatmap(CNbins, plotcol = "state") #clusters and plots the total copy number state
> plotHeatmap(CNbins, plotcol = "copy") #plots the raw "copy" data
> ```
> 
> or for plotting some individual cells:
> 
> ```
> plotCNprofile(CNbins, cellid = "cell_of_interest")
> ```

Thanks for your quick response. We will rerun HMMcopy according to your recommendation. Thanks!
